name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: anudeepy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_ANUDEEPY }}"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-image:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/my-image:latest
